/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redonz.pms.client.view.payment;

//<editor-fold defaultstate="collapsed" desc="import statements">
import com.redonz.pms.client.connector.ServerConnector;
import com.redonz.pms.client.observer.PaymentObserver;
import com.redonz.pms.client.others.IDGen;
import com.redonz.pms.client.others.Validation;
import com.redonz.pms.common.model.Customer;
import com.redonz.pms.common.model.CustomerOrder;
import com.redonz.pms.common.model.CustomerOrderDetail;
import com.redonz.pms.common.model.ObserverTO;
import com.redonz.pms.common.model.Payment;
import java.awt.Color;
import java.awt.Component;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
//</editor-fold>

/**
 *
 * @author DI_SH
 */
public class SettlePaymentForm extends javax.swing.JDialog {

    private SimpleDateFormat simpleDateFormat;
    private DefaultTableModel orderModel;
    private DefaultTableModel orderDetailModel;
    private Date date;
    private boolean loadCustomerComplete;
    private int orderChanged = -1;
    private PaymentObserver paymentObserver;
    private int searchIndex;
    private double payment;
    private String currentReservedID;

    /**
     * Creates new form SettlePaymentForm
     */
    public SettlePaymentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        date = new Date();
        initComponents();
        setLocationRelativeTo(null);
        simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        endOrderDatePicker1.setFormats(simpleDateFormat);
        orderDatePicker.setFormats(simpleDateFormat);
        orderModel = (DefaultTableModel) orderTable.getModel();
        orderDetailModel = (DefaultTableModel) orderDetailTable.getModel();
        try {
            loadCustomersToComboBox();
        } catch (NotBoundException | RemoteException | SQLException | MalformedURLException | ClassNotFoundException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            if (ex.getMessage().contains("Connection refused to host")) {
                JOptionPane.showMessageDialog(this, "Connection has corrupt or no server started....", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        try {
            paymentObserver = new PaymentObserver(this);
            ServerConnector.getServerConnector().getPaymentController().addPaymentObserver(paymentObserver);
        } catch (RemoteException | NotBoundException | MalformedURLException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        orderTable.setDefaultRenderer(Object.class, new MyRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        customerLabel = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        orderIdLabel = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderDetailTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        viewAllButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        orderDatePicker = new org.jdesktop.swingx.JXDatePicker();
        orderDateLabel = new javax.swing.JLabel();
        endOrderDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        dateRangeCheckBox = new javax.swing.JCheckBox();
        settlePaymentButton = new javax.swing.JButton();
        paymentDetailPanel = new javax.swing.JPanel();
        balancePaymentTextField = new javax.swing.JTextField();
        paymentAmountLabel = new javax.swing.JLabel();
        paymentAmountTextField = new javax.swing.JTextField();
        dueAmountTextField = new javax.swing.JTextField();
        balancePaymentLabel = new javax.swing.JLabel();
        dueAmountLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceTextField = new javax.swing.JTextField();
        paymentRecivTextField = new javax.swing.JTextField();
        paymentRecivLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        paymentHistoryButton = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(247, 247, 247));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Settle Payment");
        titleLabel.setOpaque(true);

        closeButton.setBackground(new java.awt.Color(255, 153, 153));
        closeButton.setText("Close");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        customerLabel.setText("Customer :");

        orderIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTextFieldActionPerformed(evt);
            }
        });
        orderIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                orderIdTextFieldFocusGained(evt);
            }
        });
        orderIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderIdTextFieldKeyReleased(evt);
            }
        });

        orderIdLabel.setText("Order ID : ");

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerComboBoxItemStateChanged(evt);
            }
        });
        customerComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerComboBoxFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Details"));

        orderDetailTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch No", "Description", "Unit Price", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailTable.setFocusable(false);
        orderDetailTable.setRowHeight(25);
        orderDetailTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        orderDetailTable.getTableHeader().setReorderingAllowed(false);
        orderDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                orderDetailTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(orderDetailTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("UnSettled Orders"));

        orderTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust ID", "Order ID", "Date", "Amount", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setRowHeight(25);
        orderTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        orderTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                orderTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewAllButton.setText("View All");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        orderDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDatePickerActionPerformed(evt);
            }
        });
        orderDatePicker.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                orderDatePickerFocusGained(evt);
            }
        });

        orderDateLabel.setText("Order Date :");

        endOrderDatePicker1.setEnabled(false);
        endOrderDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endOrderDatePicker1ActionPerformed(evt);
            }
        });
        endOrderDatePicker1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                endOrderDatePicker1FocusGained(evt);
            }
        });

        dateRangeCheckBox.setText("Use date range");
        dateRangeCheckBox.setEnabled(false);
        dateRangeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRangeCheckBoxActionPerformed(evt);
            }
        });

        settlePaymentButton.setBackground(new java.awt.Color(153, 248, 224));
        settlePaymentButton.setText("Settle Payment >");
        settlePaymentButton.setEnabled(false);
        settlePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settlePaymentButtonActionPerformed(evt);
            }
        });
        settlePaymentButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                settlePaymentButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                settlePaymentButtonKeyReleased(evt);
            }
        });

        paymentDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Detail"));

        balancePaymentTextField.setEditable(false);
        balancePaymentTextField.setFocusable(false);

        paymentAmountLabel.setText("Paying Amount : ");

        paymentAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentAmountTextFieldActionPerformed(evt);
            }
        });
        paymentAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentAmountTextFieldFocusGained(evt);
            }
        });
        paymentAmountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentAmountTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentAmountTextFieldKeyTyped(evt);
            }
        });

        dueAmountTextField.setEditable(false);
        dueAmountTextField.setFocusable(false);

        balancePaymentLabel.setText("Balance Payment :");

        dueAmountLabel.setText("Due Amount : ");

        balanceLabel.setText("Balance :");

        balanceTextField.setEditable(false);
        balanceTextField.setFocusable(false);

        paymentRecivTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentRecivTextFieldActionPerformed(evt);
            }
        });
        paymentRecivTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentRecivTextFieldFocusGained(evt);
            }
        });
        paymentRecivTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentRecivTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentRecivTextFieldKeyTyped(evt);
            }
        });

        paymentRecivLabel.setText("Payment Recieved :");

        javax.swing.GroupLayout paymentDetailPanelLayout = new javax.swing.GroupLayout(paymentDetailPanel);
        paymentDetailPanel.setLayout(paymentDetailPanelLayout);
        paymentDetailPanelLayout.setHorizontalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                                .addComponent(balancePaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(balancePaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailPanelLayout.createSequentialGroup()
                                .addComponent(paymentRecivLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paymentRecivTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailPanelLayout.createSequentialGroup()
                                .addComponent(dueAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dueAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailPanelLayout.createSequentialGroup()
                                .addComponent(paymentAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        paymentDetailPanelLayout.setVerticalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueAmountLabel)
                    .addComponent(dueAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentAmountLabel)
                    .addComponent(paymentAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balancePaymentLabel)
                    .addComponent(balancePaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentRecivLabel)
                    .addComponent(paymentRecivTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        paymentHistoryButton.setText("Payment Histrory");
        paymentHistoryButton.setEnabled(false);

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(settlePaymentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(orderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateRangeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endOrderDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(paymentHistoryButton))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(paymentDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewAllButton)
                .addGap(62, 62, 62))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewAllButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateRangeCheckBox)
                            .addComponent(endOrderDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDateLabel))
                        .addGap(399, 399, 399))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentHistoryButton)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton)
                        .addComponent(settlePaymentButton)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_closeButtonMouseExited

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void orderIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextFieldActionPerformed
    }//GEN-LAST:event_orderIdTextFieldActionPerformed

    private void orderIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderIdTextFieldKeyReleased
        settlePaymentButton.setEnabled(orderTable.getRowCount() > 0);
    }//GEN-LAST:event_orderIdTextFieldKeyReleased

    private void customerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerComboBoxItemStateChanged
        if (loadCustomerComplete) {
            seachByCustomer();
        }
    }//GEN-LAST:event_customerComboBoxItemStateChanged

    private void orderDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderDetailTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderDetailTableKeyPressed

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        try {
            int selectedRow = orderTable.getSelectedRow();
            String orderId = (String) orderModel.getValueAt(selectedRow, 1);
            if (currentReservedID != null) {
                ServerConnector.getServerConnector().getCustomerOrderController().releaseCustomerOrder(currentReservedID);
            }
            boolean isReserved = ServerConnector.getServerConnector().getCustomerOrderController().reserveCustomerOrder(orderId);
            if (isReserved) {
                currentReservedID = orderId;
                String custId = (String) orderModel.getValueAt(selectedRow, 0);
                for (int i = 0; i < customerComboBox.getItemCount(); i++) {
                    if (customerComboBox.getItemAt(i).toString().contains(custId)) {
                        customerComboBox.setSelectedIndex(i);
                        break;
                    }
                }
                paymentAmountTextField.setEditable(true);
                paymentAmountTextField.setFocusable(true);
                paymentHistoryButton.setEnabled(true);
                dueAmountTextField.setText(orderModel.getValueAt(selectedRow, 4).toString());
                paymentAmountTextField.setText(orderModel.getValueAt(selectedRow, 4).toString());
                try {
                    ArrayList<CustomerOrderDetail> orderDetails = ServerConnector.getServerConnector().getCustomerOderDetailController().getOrderDetailsByOrderId(orderId);
                    fillOrderDetailTable(orderDetails);
                } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
//                paymentDetailPanel.setVisible(false);
                new Thread() {
                    @Override
                    public void run() {
                        paymentAmountTextField.setFocusable(false);
                        paymentAmountTextField.setText("Payment for this Order already reserved....");
                        paymentAmountTextField.setForeground(Color.red);
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        paymentAmountTextField.setText("");
                        paymentAmountTextField.setForeground(Color.BLACK);
                    }
                }.start();
            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_orderTableMouseClicked

    private void orderTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderTableKeyPressed
    }//GEN-LAST:event_orderTableKeyPressed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void dateRangeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRangeCheckBoxActionPerformed

        endOrderDatePicker1.setEnabled(dateRangeCheckBox.isSelected());
        endOrderDatePicker1.setDate(date);
    }//GEN-LAST:event_dateRangeCheckBoxActionPerformed

    private void endOrderDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endOrderDatePicker1ActionPerformed
        searchDateRange();
    }//GEN-LAST:event_endOrderDatePicker1ActionPerformed

    private void orderDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDatePickerActionPerformed
        dateRangeCheckBox.setEnabled(orderDatePicker.getDate() != null);
        if (!dateRangeCheckBox.isSelected()) {
            searchByDate();
        } else {
            searchDateRange();
        }
    }//GEN-LAST:event_orderDatePickerActionPerformed

    private void settlePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settlePaymentButtonActionPerformed
        try {
            String lastPaymentId = ServerConnector.getServerConnector().getPaymentController().getLastPaymentId();
            String paymentId = IDGen.getNextId(lastPaymentId != null ? lastPaymentId : "P0000");
//
            int selectedRow = orderTable.getSelectedRow();
            Payment payment = new Payment(paymentId, orderModel.getValueAt(selectedRow, 1).toString(), ServerConnector.getServerConnector().getDateController().getCurrentDate(), Double.parseDouble(paymentAmountTextField.getText()), 1);
            paymentObserver.setChanged(true);
            boolean res = ServerConnector.getServerConnector().getPaymentController().savePayment(payment);
            if (res) {
                JOptionPane.showMessageDialog(this, "Saved Successfully....");
                paymentAmountTextField.setText("");
                orderTable.setValueAt(balancePaymentTextField.getText(), selectedRow, 4);
            }
            new Thread() {
                @Override
                public void run() {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        paymentObserver.setChanged(false);
                    } catch (RemoteException ex) {
                        Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();

        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CustomerPaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_settlePaymentButtonActionPerformed

    private void settlePaymentButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_settlePaymentButtonKeyPressed
        if (evt.getKeyCode() == 10) {
            settlePaymentButton.doClick();
        }
    }//GEN-LAST:event_settlePaymentButtonKeyPressed

    private void settlePaymentButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_settlePaymentButtonKeyReleased
    }//GEN-LAST:event_settlePaymentButtonKeyReleased

    private void paymentAmountTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentAmountTextFieldKeyReleased

        Validation.validatePriceText(paymentAmountTextField);
        settlePaymentButton.setEnabled(!paymentAmountTextField.getText().isEmpty() && !paymentRecivTextField.getText().isEmpty());
        String text = paymentAmountTextField.getText();
        if (text != null && !text.isEmpty()) {
            payment = Double.parseDouble(text);
            double due = Double.parseDouble(dueAmountTextField.getText());
            double balance = due - payment;
            int caretPosition = paymentAmountTextField.getCaretPosition();
            if (balance < 0) {
                text = text.substring(0, caretPosition - 1) + text.substring(caretPosition);
                paymentAmountTextField.setText(text);
                payment = Double.parseDouble(text);
            } else {
                balancePaymentTextField.setText(balance + "");
            }


        }
    }//GEN-LAST:event_paymentAmountTextFieldKeyReleased

    private void paymentAmountTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentAmountTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentAmountTextFieldKeyTyped

    private void paymentAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentAmountTextFieldActionPerformed
        paymentRecivTextField.requestFocus();
    }//GEN-LAST:event_paymentAmountTextFieldActionPerformed

    private void orderIdTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orderIdTextFieldFocusGained
        searchIndex = 1;
    }//GEN-LAST:event_orderIdTextFieldFocusGained

    private void customerComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerComboBoxFocusGained
        searchIndex = 2;
    }//GEN-LAST:event_customerComboBoxFocusGained

    private void orderDatePickerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orderDatePickerFocusGained
        searchIndex = 3;
    }//GEN-LAST:event_orderDatePickerFocusGained

    private void endOrderDatePicker1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endOrderDatePicker1FocusGained
        searchIndex = 4;
    }//GEN-LAST:event_endOrderDatePicker1FocusGained

    private void paymentAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentAmountTextFieldFocusGained
        paymentAmountTextField.selectAll();
    }//GEN-LAST:event_paymentAmountTextFieldFocusGained

    private void paymentRecivTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentRecivTextFieldActionPerformed
        settlePaymentButton.doClick();
    }//GEN-LAST:event_paymentRecivTextFieldActionPerformed

    private void paymentRecivTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentRecivTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentRecivTextFieldFocusGained

    private void paymentRecivTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentRecivTextFieldKeyReleased
        Validation.validatePriceText(paymentRecivTextField);
        settlePaymentButton.setEnabled(!paymentAmountTextField.getText().isEmpty() && !paymentRecivTextField.getText().isEmpty());
        String text = paymentRecivTextField.getText();
        if (text != null && !text.isEmpty()) {
            double paymentReciv = Double.parseDouble(text);

            double balance = paymentReciv - payment;
            int caretPosition = paymentAmountTextField.getCaretPosition();
            if (balance < 0) {
                balanceTextField.setText("0.00");
            } else {
                balanceTextField.setText(balance + "");
            }


        }
    }//GEN-LAST:event_paymentRecivTextFieldKeyReleased

    private void paymentRecivTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentRecivTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentRecivTextFieldKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ServerConnector.getServerConnector().getCustomerOrderController().releaseCustomerOrder(currentReservedID);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettlePaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SettlePaymentForm dialog = new SettlePaymentForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    //<editor-fold defaultstate="collapsed" desc="Variable Declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balancePaymentLabel;
    private javax.swing.JTextField balancePaymentTextField;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox customerComboBox;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JCheckBox dateRangeCheckBox;
    private javax.swing.JLabel dueAmountLabel;
    private javax.swing.JTextField dueAmountTextField;
    private org.jdesktop.swingx.JXDatePicker endOrderDatePicker1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel orderDateLabel;
    private org.jdesktop.swingx.JXDatePicker orderDatePicker;
    private javax.swing.JTable orderDetailTable;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JTextField orderIdTextField;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel paymentAmountLabel;
    private javax.swing.JTextField paymentAmountTextField;
    private javax.swing.JPanel paymentDetailPanel;
    private javax.swing.JButton paymentHistoryButton;
    private javax.swing.JLabel paymentRecivLabel;
    private javax.swing.JTextField paymentRecivTextField;
    private javax.swing.JButton settlePaymentButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewAllButton;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    private void fillOrderTable(ArrayList<CustomerOrder> orders) {
        orderModel.setRowCount(0);
        for (CustomerOrder customerOrder : orders) {
            orderModel.addRow(new Object[]{customerOrder.getCustId(), customerOrder.getOrderId(), customerOrder.getDate(), customerOrder.getTotalAmount(), customerOrder.getBalance()});
        }
    }

    private void fillOrderDetailTable(ArrayList<CustomerOrderDetail> orderDetails) throws NotBoundException, MalformedURLException, RemoteException, SQLException, ClassNotFoundException {
        orderDetailModel.setRowCount(0);
        for (CustomerOrderDetail customerOrderDetail : orderDetails) {
            String desc = ServerConnector.getServerConnector().getBatchItemController().getItemByItemCode(customerOrderDetail.getItemCode()).getDescription();
            orderDetailModel.addRow(new Object[]{customerOrderDetail.getBatchNo(), desc, customerOrderDetail.getUnitprice(), customerOrderDetail.getQty()});
        }
    }

    private void searchDateRange() {
        Date bDate = orderDatePicker.getDate();
        Date eDate = endOrderDatePicker1.getDate();
        String biginDate = simpleDateFormat.format(bDate);
        String endDate = simpleDateFormat.format(eDate);
        try {
            ArrayList<CustomerOrder> orders = ServerConnector.getServerConnector().getCustomerOrderController().getOrdersByDateRange(biginDate, endDate);
            fillOrderTable(orders);
            checkOrderTable();
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
//        paymentRecievedTextField.setEditable(orderTable.getRowCount() > 0);
        paymentHistoryButton.setEnabled(orderTable.getRowCount() > 0);
    }

    private void loadCustomersToComboBox() throws NotBoundException, RemoteException, SQLException, MalformedURLException, ClassNotFoundException {
        loadCustomerComplete = false;
        ArrayList<Customer> allCustomers = ServerConnector.getServerConnector().getCustomerController().getAllCustomers();
        customerComboBox.removeAllItems();
        for (Customer customer : allCustomers) {
            customerComboBox.addItem(customer);
        }
        loadCustomerComplete = true;
    }

    public void notifyChanges(ObserverTO observerTO) {
        if (observerTO.getAction().equals(ObserverTO.ADD)) {

            if (observerTO.getObj() instanceof Payment) {
                Payment payment = (Payment) observerTO.getObj();
                if (payment.getState() == 1) {
                    for (int i = 0; i < orderTable.getRowCount(); i++) {
                        if (orderTable.getValueAt(i, 1).equals(payment.getOrderId())) {
                            orderChanged = i;
                            orderTable.setValueAt(((Double) orderTable.getValueAt(i, 4)) - payment.getAmount(), i, 4);
                            break;
                        }
                    }

                    orderTable.repaint();
                    JOptionPane.showMessageDialog(this, "Payment done for order : " + payment.getOrderId());
                    new Thread() {
                        @Override
                        public void run() {
                            try {
                                Thread.sleep(5000);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            orderChanged = -1;
                            orderTable.repaint();
                        }
                    }.start();
                } else {
                    switch (searchIndex) {
                        case 2:
                            seachByCustomer();
                            break;
                        case 3:
                            if (!dateRangeCheckBox.isSelected()) {
                                searchByDate();
                            } else {
                                searchDateRange();
                            }
                            break;
                        case 4:
                            searchDateRange();
                            break;
                        default:
                            throw new AssertionError();
                    }
                    JOptionPane.showMessageDialog(this, "Payment done for new order : " + payment.getOrderId());
                }
            }
        }
    }

    private void seachByCustomer() {
        String custId = ((Customer) customerComboBox.getSelectedItem()).getCustId();
        try {
            ArrayList<CustomerOrder> ordersByCustId = ServerConnector.getServerConnector().getCustomerOrderController().getOrdersByCustId(custId);
            fillOrderTable(ordersByCustId);
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        checkOrderTable();
    }

    private void searchByDate() {
        Date date = orderDatePicker.getDate();
        String orderDate = simpleDateFormat.format(date);
        try {
            ArrayList<CustomerOrder> ordersByOrderDate = ServerConnector.getServerConnector().getCustomerOrderController().getOrdersByOrderDate(orderDate);
            fillOrderTable(ordersByOrderDate);
            checkOrderTable();
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void checkOrderTable() {
        boolean b = orderTable.getRowCount() > 0;

        paymentHistoryButton.setEnabled(b);
        if (!b) {
            new Thread() {
                @Override
                public void run() {
                    msgLabel.setText("No any un settled orders found...");
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SettlePaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    msgLabel.setText("");
                }
            }.start();
        }
    }

    class MyRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setBackground(null);
            setForeground(Color.BLACK);
            Component tableCellRendererComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
            if (row == orderChanged) {

                setBackground(new Color(255, 153, 153));
                setForeground(Color.WHITE);
                if (column == 4) {
                    setForeground(Color.GRAY);
                }
            }

            return tableCellRendererComponent;
        }
    }
}
